/* eslint-disable import/prefer-default-export */
// #flow

export const ActionTypes = {
	LOAD_PROFILES_TYPE: "ssconnect/App/LOAD_PROFILES_TYPE",
	LOAD_PROFILES_END_TYPE: "ssconnect/App/LOAD_PROFILES_END_TYPE",
	ADD_PROFILE_TYPE: "ssconnect/App/ADD_PROFILE_TYPE",
	DELETE_PROFILE_TYPE: "ssconnect/App/DELETE_PROFILE_TYPE",
	DELETE_PROFILE_END_TYPE: "ssconnect/App/DELETE_PROFILE_END_TYPE",
	MOVE_PROFILE_TYPE: "ssconnect/App/MOVE_PROFILE_TYPE",
	MOVE_PROFILE_END_TYPE: "ssconnect/App/MOVE_PROFILE_END_TYPE",

	LOAD_READS_TYPE: "ssconnect/App/LOAD_READS_TYPE",
	LOAD_READS_END_TYPE: "ssconnect/App/LOAD_READS_END_TYPE",
	ADD_READ_TYPE: "ssconnect/App/ADD_READ_TYPE",

	LOAD_STORIES_TYPE: "ssconnect/App/LOAD_STORIES_TYPE",
	LOAD_STORIES_END_TYPE: "ssconnect/App/LOAD_STORIES_END_TYPE",
	LOAD_STORIES_ERROR_TYPE: "ssconnect/App/LOAD_STORIES_ERROR_TYPE",

	UPDATE_PAGE_TYPE: "ssconnect/App/UPDATE_PAGE_TYPE",

	LOAD_CONFIG_TYPE: "ssconnect/App/LOAD_CONFIG_TYPE",
	LOAD_CONFIG_END_TYPE: "ssconnect/App/LOAD_CONFIG_END_TYPE",
	TOGGLE_IAB_CONFIG_TYPE: "ssconnect/App/TOGGLE_CONFIG_TYPE",
}
